"""Section aligner service using LangChain to generate the MigrationPlan."""

from __future__ import annotations

import json
from typing import Optional, Union
from loguru import logger
from langchain_core.messages import SystemMessage, HumanMessage

from app.services.llm.chain_factory import ChainFactory
from app.services.llm.rate_limiter import LLMRateLimiter
from app.services.llm.prompts.migration_planner import (
    PLANNER_SYSTEM_PROMPT,
    PLANNER_USER_PROMPT_TEMPLATE,
)
from app.services.migration.schemas import (
    TemplateRawProfile,
    ContentSummary,
    MigrationPlan,
    SlimTemplateProfile,
)


class SectionAligner:
    """Orchestrates the LLM planning call to produce a structured MigrationPlan."""

    def __init__(self, chain_factory: ChainFactory, rate_limiter: LLMRateLimiter):
        self._chain_factory = chain_factory
        self._rate_limiter = rate_limiter

    async def create_migration_plan(
        self,
        template_profile: TemplateRawProfile,
        content_summary: ContentSummary,
        slim_profile: Optional[Union[SlimTemplateProfile, dict]] = None,
    ) -> MigrationPlan:
        """Send template profile, rules, and content summary to LLM to produce a MigrationPlan."""
        logger.info("Calling LLM Migration Planner to generate MigrationPlan...")

        structured_llm = self._chain_factory.create_structured_planner(MigrationPlan)

        if slim_profile:
            slim_json = (
                slim_profile.model_dump_json(indent=2)
                if hasattr(slim_profile, "model_dump_json")
                else json.dumps(slim_profile, indent=2)
            )
        else:
            slim_json = "(No specific template instructions or rules provided)"

        profile_json = (
            template_profile.model_dump_json(indent=2)
            if hasattr(template_profile, "model_dump_json")
            else json.dumps(template_profile, indent=2)
        )

        sop_summary_json = content_summary.model_dump_json(indent=2)

        human_prompt_content = PLANNER_USER_PROMPT_TEMPLATE.format(
            template_instructions_and_rules=slim_json,
            template_profile=profile_json,
            sop_content_summary=sop_summary_json,
        )

        system_msg = SystemMessage(content=PLANNER_SYSTEM_PROMPT)
        human_msg = HumanMessage(content=human_prompt_content)

        plan: MigrationPlan = await self._rate_limiter.execute(
            coro_factory=lambda: structured_llm.ainvoke([system_msg, human_msg]),
            task_name="migration_planner",
        )

        logger.info(
            f"MigrationPlan successfully generated by LLM: {len(plan.section_plans)} section plans, "
            f"{len(plan.placeholder_tables)} placeholder table plans, confidence={plan.overall_confidence:.2f}"
        )

        return plan
