"""Section aligner service using LangChain to generate the MigrationPlan."""

from __future__ import annotations

from loguru import logger
from langchain_core.messages import SystemMessage, HumanMessage

from app.services.llm.chain_factory import ChainFactory
from app.services.llm.rate_limiter import LLMRateLimiter
from app.services.llm.prompts.migration_planner import PLANNER_SYSTEM_PROMPT
from app.services.migration.schemas import (
    TemplateRawProfile,
    ContentSummary,
    MigrationPlan,
)


class SectionAligner:
    """Orchestrates the LLM planning call to produce a structured MigrationPlan."""

    def __init__(self, chain_factory: ChainFactory, rate_limiter: LLMRateLimiter):
        self._chain_factory = chain_factory
        self._rate_limiter = rate_limiter

    async def create_migration_plan(
        self,
        template_profile: TemplateRawProfile,
        content_summary: ContentSummary,
    ) -> MigrationPlan:
        """Send template profile and content summary to LLM to produce a MigrationPlan."""
        logger.info("Calling LLM Migration Planner to generate MigrationPlan...")

        structured_llm = self._chain_factory.create_structured_planner(MigrationPlan)

        system_msg = SystemMessage(content=PLANNER_SYSTEM_PROMPT)
        human_msg = HumanMessage(
            content=(
                f"TEMPLATE_PROFILE:\n{template_profile.model_dump_json(indent=2)}\n\n"
                f"CONTENT_SUMMARY:\n{content_summary.model_dump_json(indent=2)}"
            )
        )

        plan: MigrationPlan = await self._rate_limiter.execute(
            coro_factory=lambda: structured_llm.ainvoke([system_msg, human_msg]),
            task_name="migration_planner",
        )

        logger.info(
            f"MigrationPlan successfully generated by LLM: {len(plan.section_plans)} section plans, "
            f"{len(plan.placeholder_tables)} placeholder table plans, confidence={plan.overall_confidence:.2f}"
        )

        return plan
